# Site settings
author: Bernadette Davis
title: 
header-img: img/home-bg.png
email: bsd231@nyu.edu
copyright_name: Bernadette Davis
description: > # this means to ignore newlines until "baseurl:"
  
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  boom100100

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
